# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

use_frameworks!

target 'dis-ios' do
    pod 'SwiftyJSON'
end

target 'dis-iosTests' do
    pod 'Nocilla'
    pod 'Nimble'
end

target 'dis-iosUITests' do
    pod 'GCDWebServer'
end

